
# SMTP/Email configuration
sender.email=csspoof
smtp.app.password=qgbg ywgk apsd sthm
receiver.email=srivatsa.a.malali@gmail.com

# Timing Configuration
check.interval.seconds=3
# check.interval.minutes=3  # legacy fallback

